[project]
name = "mcs-ambient-light"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jens <jens.jens@live.dk>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "<3.11"
